name: fashion_ecommerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  advance_notification: ^1.0.6
  badges: ^2.0.3
  line_icons: ^2.0.1
  bottom_bar_matu: ^1.3.0
  flutter_svg: ^2.0.9

  firebase_core: ^2.24.2
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf
